name: Test action
description: test
author: me
branding:
  icon: check-square
  color: green
inputs:
  report-file:
    description: The location of the report.txt file
    required: true
  coverage-threshold:
    description: Code coverage threshold 0..100
    required: false
    default: "0"
runs:
  using: node20
  main: src/main.js